### ISSUE TITLE
Docker image build error - Incorrect CA certificate checksum

### ISSUE THREAD

**Issue by navganti** [zytedata/zyte-smartproxy-headless-proxy#33]
### System Information
OS: Ubuntu 18.04
Dockerfile: https://hub.docker.com/layers/scrapinghub/crawlera-headless-proxy/1.2.2/images/sha256-e0b3055dbe9f6c35320dbfa275e43fa03e54727f4d9f99f70333da779bae93e4?context=explore

### Steps to reproduce
- Follow the Docker container instructions from the README [here](https://github.com/scrapinghub/crawlera-headless-proxy#docker-container), using the latest tagged release.

### Expected Result
- Docker container builds without issue.

### Actual Result
```bash
Incorrect CA certificate checksum 35a7044410907484ad3eb23bd5623bf91f688c16
```

It appears that the Dockerfile tries to add the CA certificate from the following URL, but this URL doesn't exist anymore with the shift to Zyte. Where can this be found?

```docker
ADD https://doc.scrapinghub.com/_downloads/639adb203cdcb1249a5a7618d9f4fa96/crawlera-ca.crt \
 /usr/local/share/ca-certificates/crawlera-ca.crt
```

**Comment by navganti** [comment]
Oh - I think I found the correct link from this [article](https://support.zyte.com/support/solutions/articles/22000188407-fetching-https-pages-with-crawlera).

It looks like this is the correct link: https://docs.zyte.com/_downloads/753f39eae366f4d8c42249b7b1246c29/zyte-proxy-ca.crt

**Comment by AndreuJove** [comment]
Same error here. How did you solved?

**Comment by spandansingh** [comment]
> Oh - I think I found the correct link from this [article](https://support.zyte.com/support/solutions/articles/22000188407-fetching-https-pages-with-crawlera).
> 
> It looks like this is the correct link: https://docs.zyte.com/_downloads/753f39eae366f4d8c42249b7b1246c29/zyte-proxy-ca.crt

This link is not working as well.

**Comment by kilimchoi** [comment]
@realslimshanky any ideas?

**Comment by realslimshanky** [comment]
cc: @krant @janin

**Comment by krant** [comment]
Fixed in https://github.com/zytedata/zyte-smartproxy-headless-proxy/pull/63

@realslimshanky thanks for tagging us, mate! Cheers :)
